### ISSUE TITLE
Remove .enum from Spreadsheet Property IDs

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect-backend-test#5]
Currently the Camunda Modeler Form Field Properties used to specify using a spreadsheet to populate the values and labels are:  

File name - enum.options.name
Value column - enum.options.value.column
Label column - enum.options.label.column

These are use both for Form Field Types enum and custom type-autocomplete.  Having enum as the lead word for these properties is confusing when using for the  custom type-autocomplete Form Field Type.

Additionally, the Property to turn on the search feature, which is only available in the custom type-autocomplete Form Field Type is:
enum.options.lookup
This again is confusing since it cannot be used with the enum Form Field Type at all.  

A suggesting on what to change these to is:
File name - spreadsheet.name
Value column - spreadsheet.value.column
Label column - spreadsheet.label.column

As for the enum.options.lookup Property, if there is never a situation where that would be set to False, can it be omitted all together?  If this is a use case for False, then spreadsheet.lookup would follow the previous suggestoins.

**Comment by danfunk** [comment]
This was fixed some time ago.
